name: gift_bouqet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6 # Downgraded to resolve conflict with flutter_map
  shared_preferences: ^2.5.3
  intl: ^0.18.0
  crypto: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  logger: ^2.5.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  url_launcher: ^6.1.7
  flutter_compass: 0.8.1
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.0.1
  provider: ^6.0.5
  sensors_plus: ^5.0.1
  email_validator: ^2.0.1
  image_picker: ^0.8.5+3
  accordion: ^2.2.1
  google_fonts: ^4.0.0
  uuid: ^4.3.3
  timezone: ^0.9.0 # Added for time zone conversion


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  # Optional: To use adaptive icons on Android 8.0 (API 26) and above
  # If you enable this, you will need a separate foreground image and a background color/image
  # adaptive_icon_background: "#ffffff" # Hex color code
  # adaptive_icon_foreground: "assets/foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21
  # Optional: To use adaptive icons on Android 8.0 (API 26) and above
  # If you enable this, you will need a separate foreground image and a background color/image
  # adaptive_icon_background: "#ffffff" # Hex color code
  # adaptive_icon_foreground: "assets/foreground.png"